interfaces: 
 - interface:
   name: Loopback0
   address: 10.0.0.3
   mask: 255.255.255.255
   enabled: True
 - interface:
   name: Ethernet1/1
   address: 172.30.128.14
   mask: 255.255.255.252
   enabled: True
 - interface:
   name: Ethernet1/2
   address: 172.30.128.6
   mask: 255.255.255.252
   enabled: True
 - interface:
   name: Ethernet1/3
   address: 172.30.128.17
   mask: 255.255.255.252
   enabled: True
