
- name: List interface directory
  find:
    paths: roles/models/files/{{scope}}
    patterns: "*{{ inventory_hostname }}.yml"
    recurse: yes
    file_type: file
  register: Files
  delegate_to: localhost

- name: Include interface vars
  include_vars:
    file: roles/models/files/{{scope}}/{{ inventory_hostname }}.yml
  when: Files.files != []
  delegate_to: localhost

- name: validate ip addr
  assert:
    that:
      - item.address | ipaddr 
    fail_msg: "Endereco invalido"
  with_items: "{{ interfaces }}"
  when: Files.files != []

- name: Make Config
  template:
    src: "{{scope}}.j2"
    dest: cfg/{{ inventory_hostname }}.cfg
    mode: 0777
  when: Files.files != []
  delegate_to: localhost
